/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function BezelHead(props) {
  const { nodes, materials } = useGLTF('models/head/Bezel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.ROUND001.geometry}
        material={materials['ROSE GOLD']}
        position={[0, 10.041, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/head/Bezel.glb')
