/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HaloHead(props) {
  const { nodes, materials } = useGLTF('models/head/Halo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.round001.geometry}
        material={materials['ROSE GOLD.004']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.hidden_halo001.geometry}
        material={materials['ROSE GOLD.002']}
        position={[0, 0.096, 0]}
        scale={0.965}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['hidden_halo_-_diamonds001'].geometry}
        material={materials['DIAMOND.001']}
        position={[0, 0.096, 0]}
        scale={0.965}
      />
    </group>
  )
}

useGLTF.preload('models/head/Halo.glb')
