/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\head\Princess-SideStones.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import DiamondMaterial from "../DiamondMaterial";
import { Color } from "three";

export default function PrincessSideStones(props) {
  const { nodes, materials } = useGLTF("./models/head/Princess-SideStones.glb");
  materials["ROSE GOLD.005"].metalness = props.metalness;
  materials["ROSE GOLD.005"].roughness = props.roughness;
  materials["ROSE GOLD.005"].color = new Color(props.color);
  return (
    <group {...props} dispose={null}>
      <group
        position={[-3.907, 7.551, 0]}
        rotation={[Math.PI / 2, 0.494, 0]}
        scale={0.642}
      >
        <mesh
          geometry={nodes["all-diamonds929_1"].geometry}
          material={materials["DIAMOND.005"]}
        >
          <DiamondMaterial
            envMap={props.diamondTextureMap}
            bounces={6}
            ior={2.43}
            aberrationStrength={0.012}
            fresnel={0.1}
          />
        </mesh>
        <mesh
          geometry={nodes["all-diamonds929_2"].geometry}
          material={materials["ROSE GOLD.005"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/head/Princess-SideStones.glb");
