/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";

export function RoundHead(props) {
  const { nodes, materials } = useGLTF("/models/head/Round.glb");
  console.log(materials["ROSE GOLD"].color, props);
  materials["ROSE GOLD"].metalness = props.metalness;
  materials["ROSE GOLD"].roughness = props.roughness;
  materials["ROSE GOLD"].color = new Color(props.color);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["4_prong"].geometry}
        material={materials["ROSE GOLD"]}
      />
    </group>
  );
}

useGLTF.preload("/models/head/Round.glb");
