/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\head\Round-SideStones.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";
import DiamondMaterial from "../DiamondMaterial";

export default function RoundSideStones(props) {
  const { nodes, materials } = useGLTF("./models/head/Round-SideStones.glb");
  materials["ROSE GOLD.002"].metalness = props.metalness;
  materials["ROSE GOLD.002"].roughness = props.roughness;
  materials["ROSE GOLD.002"].color = new Color(props.color);
  return (
    <group {...props} dispose={null}>
      <group
        position={[-2.395, 8.264, -0.025]}
        rotation={[0.018, 0, -0.098]}
        scale={2.961}
      >
        <mesh
          geometry={nodes.diamond002.geometry}
          material={materials["DIAMOND.002"]}
        >
          <DiamondMaterial
            envMap={props.diamondTextureMap}
            bounces={6}
            ior={2.43}
            aberrationStrength={0.012}
            fresnel={0.1}
          />
        </mesh>
        <mesh
          geometry={nodes.diamond002_1.geometry}
          material={materials["ROSE GOLD.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/head/Round-SideStones.glb");
