/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ThreeStoneHead(props) {
  const { nodes, materials } = useGLTF('models/head/ThreeStone.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-2.842, 0.307, 0]} rotation={[Math.PI / 2, 0.196, Math.PI]} scale={0.654}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.oval004.geometry}
          material={materials['ROSE GOLD.003']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.oval004_1.geometry}
          material={materials['DIAMOND.003']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('models/head/ThreeStone.glb')
