/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useLoader } from "@react-three/fiber";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";
import { diamondTexture } from "../../assets";
import DiamondMaterial from "../DiamondMaterial";
import { useClonedMaterial, syncMetalMatProps } from "../materialUtils";

export function ChannelShank(props) {
  const { nodes, materials } = useGLTF("models/shank/Channel.glb");
  const roseGold = useClonedMaterial(materials["ROSE GOLD"]);
  syncMetalMatProps(roseGold, props);

  const envMap = useLoader(RGBELoader, "hdr/metal3.hdr");
  envMap.mapping = THREE.EquirectangularReflectionMapping;
  envMap.colorSpace = THREE.SRGBColorSpace;
  envMap.repeat.set(0, 0);
  envMap.wrapS = THREE.RepeatWrapping;
  envMap.wrapT = THREE.RepeatWrapping;
  const map = useLoader(THREE.TextureLoader, diamondTexture);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.diamond003.geometry}
        material={materials.DIAMOND}
        position={[0, -1.518, 0]}
      >
        <DiamondMaterial
          envMap={props.diamondTextureMap}
          bounces={6}
          ior={2.43}
          aberrationStrength={0.012}
          fresnel={0.1}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.metal003.geometry}
        material={roseGold}
        position={[0, -1.518, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/Channel.glb");
