/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { MeshRefractionMaterial, useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useLoader } from "@react-three/fiber";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";
import { diamondTexture } from "../../assets";

export function ChannelShank(props) {
  const { nodes, materials } = useGLTF("models/shank/Channel.glb");
  materials["ROSE GOLD"].metalness = props.metalness;
  materials["ROSE GOLD"].roughness = props.roughness;
  materials["ROSE GOLD"].color = new THREE.Color(props.color);

  const envMap = useLoader(RGBELoader, "hdr/metal3.hdr");
  envMap.mapping = THREE.EquirectangularReflectionMapping;
  envMap.colorSpace = THREE.SRGBColorSpace;
  envMap.repeat.set(0, 0);
  envMap.wrapS = THREE.RepeatWrapping;
  envMap.wrapT = THREE.RepeatWrapping;
  const map = useLoader(THREE.TextureLoader, diamondTexture);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.diamond003.geometry}
        material={materials.DIAMOND}
        position={[0, -1.518, 0]}
      >
        <MeshRefractionMaterial
          map={map}
          envMap={envMap}
          envMapIntensity={5}
          aberrationStrength={0.01}
          toneMapped={true}
          bounces={4}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.metal003.geometry}
        material={materials["ROSE GOLD"]}
        position={[0, -1.518, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/Channel.glb");
