/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function KnifeEdgeShank(props) {
  const { nodes, materials } = useGLTF("models/shank/KnifeEdge.glb");
  materials["ROSE GOLD"].metalness = props.metalness;
  materials["ROSE GOLD"].roughness = props.roughness;
  materials["ROSE GOLD"].color = new THREE.Color(props.color);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.knife_edge.geometry}
        material={materials["ROSE GOLD"]}
        position={[0, -0.886, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/KnifeEdge.glb");
