/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function PlainShank(props) {
  const { nodes, materials } = useGLTF("models/shank/Plain.glb");
  materials["ROSE GOLD"].metalness = props.metalness;
  materials["ROSE GOLD"].roughness = props.roughness;
  materials["ROSE GOLD"].color = new THREE.Color(props.color);

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plain.geometry}
        material={materials["ROSE GOLD"]}
        position={[0, -1.605, 0]}
        scale={[1.21, 1.21, 1.386]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/Plain.glb");
