/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { MeshRefractionMaterial, useGLTF } from "@react-three/drei";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";
import { useLoader } from "@react-three/fiber";
import { diamondTexture } from "../../assets";
import * as THREE from "three";

export function PlateProngShank(props) {
  const { nodes, materials } = useGLTF("models/shank/PlateProng.glb");
  materials["ROSE GOLD"].metalness = props.metalness;
  materials["ROSE GOLD"].roughness = props.roughness;
  materials["ROSE GOLD"].color = new THREE.Color(props.color);
  const envMap = useLoader(RGBELoader, "hdr/metal3.hdr");
  envMap.mapping = THREE.EquirectangularReflectionMapping;
  envMap.colorSpace = THREE.SRGBColorSpace;
  envMap.repeat.set(0, 0);
  envMap.wrapS = THREE.RepeatWrapping;
  envMap.wrapT = THREE.RepeatWrapping;
  const map = useLoader(THREE.TextureLoader, diamondTexture);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.diamond002.geometry}
        material={materials.DIAMOND}
        position={[0, -1.617, 0]}
        scale={1.028}
      >
        <MeshRefractionMaterial
          map={map}
          envMap={envMap}
          envMapIntensity={5}
          aberrationStrength={0.01}
          toneMapped={true}
          bounces={4}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.metal002.geometry}
        material={materials["ROSE GOLD"]}
        position={[0, -1.614, 0]}
        scale={[1.005, 1.005, 0.996]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plain001.geometry}
        material={materials["ROSE GOLD"]}
        position={[0, -1.605, 0]}
        scale={[1.21, 1.21, 1.386]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/PlateProng.glb");
