/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RGBELoader } from "three/examples/jsm/loaders/RGBELoader.js";
import { useLoader } from "@react-three/fiber";
import { diamondTexture } from "../../assets";
import * as THREE from "three";
import DiamondMaterial from "../DiamondMaterial";
import { useClonedMaterial, syncMetalMatProps } from "../materialUtils";

export function PlateProngShank(props) {
  const { nodes, materials } = useGLTF("models/shank/PlateProng.glb");
  const roseGold = useClonedMaterial(materials["ROSE GOLD"]);
  syncMetalMatProps(roseGold, props);
  const envMap = useLoader(RGBELoader, "hdr/metal3.hdr");
  envMap.mapping = THREE.EquirectangularReflectionMapping;
  envMap.colorSpace = THREE.SRGBColorSpace;
  envMap.repeat.set(0, 0);
  envMap.wrapS = THREE.RepeatWrapping;
  envMap.wrapT = THREE.RepeatWrapping;
  const map = useLoader(THREE.TextureLoader, diamondTexture);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.diamond002.geometry}
        material={materials.DIAMOND}
        position={[0, -1.617, 0]}
        scale={1.028}
      >
        <DiamondMaterial
          envMap={props.diamondTextureMap}
          bounces={6}
          ior={2.43}
          aberrationStrength={0.012}
          fresnel={0.1}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.metal002.geometry}
        material={roseGold}
        position={[0, -1.614, 0]}
        scale={[1.005, 1.005, 0.996]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plain001.geometry}
        material={roseGold}
        position={[0, -1.605, 0]}
        scale={[1.21, 1.21, 1.386]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/PlateProng.glb");
