/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useClonedMaterial, syncMetalMatProps } from "../materialUtils";

export function SplitShank(props) {
  const { nodes, materials } = useGLTF("models/shank/Split.glb");
  const roseGold = useClonedMaterial(materials["ROSE GOLD"]);
  syncMetalMatProps(roseGold, props);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plain.geometry}
        material={roseGold}
        position={[0, -1.163, 0]}
        scale={[1.21, 1.21, 1.515]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/Split.glb");
