/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SplitShank(props) {
  const { nodes, materials } = useGLTF('models/shank/Split.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.plain.geometry}
        material={materials['ROSE GOLD']}
        position={[0, -1.163, 0]}
        scale={[1.21, 1.21, 1.515]}
      />
    </group>
  )
}

useGLTF.preload('models/shank/Split.glb')
