/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function TwistedShank(props) {
  const { nodes, materials } = useGLTF('models/shank/Twisted.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.twisted.geometry}
        material={materials['ROSE GOLD']}
        position={[0.031, -1.299, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/shank/Twisted.glb')