/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useClonedMaterial, syncMetalMatProps } from "../materialUtils";

export function WidePlainShank(props) {
  const { nodes, materials } = useGLTF("models/shank/WidePlain.glb");
  const roseGold = useClonedMaterial(materials["ROSE GOLD"]);
  syncMetalMatProps(roseGold, props);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wide_plain.geometry}
        material={roseGold}
        position={[0, -0.823, 0]}
      />
    </group>
  );
}

useGLTF.preload("models/shank/WidePlain.glb");
