/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WidePlainShank(props) {
  const { nodes, materials } = useGLTF('models/shank/WidePlain.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.wide_plain.geometry}
        material={materials['ROSE GOLD']}
        position={[0, -0.823, 0]}
      />
    </group>
  )
}

useGLTF.preload('models/shank/WidePlain.glb')